Traceback (most recent call last):
  File "main.py", line 168, in updateinfo
UnboundLocalError: local variable 'info' referenced before assignment
Traceback (most recent call last):
  File "main.py", line 168, in updateinfo
UnboundLocalError: local variable 'info' referenced before assignment
Traceback (most recent call last):
  File "main.py", line 168, in updateinfo
UnboundLocalError: local variable 'info' referenced before assignment
Traceback (most recent call last):
  File "main.py", line 168, in updateinfo
UnboundLocalError: local variable 'info' referenced before assignment
Traceback (most recent call last):
  File "main.py", line 168, in updateinfo
UnboundLocalError: local variable 'info' referenced before assignment
Traceback (most recent call last):
  File "main.py", line 168, in updateinfo
UnboundLocalError: local variable 'info' referenced before assignment
Traceback (most recent call last):
  File "main.py", line 168, in updateinfo
UnboundLocalError: local variable 'info' referenced before assignment
Traceback (most recent call last):
  File "main.py", line 168, in updateinfo
UnboundLocalError: local variable 'info' referenced before assignment
Traceback (most recent call last):
  File "main.py", line 168, in updateinfo
UnboundLocalError: local variable 'info' referenced before assignment
Traceback (most recent call last):
  File "main.py", line 168, in updateinfo
UnboundLocalError: local variable 'info' referenced before assignment
Traceback (most recent call last):
  File "main.py", line 168, in updateinfo
UnboundLocalError: local variable 'info' referenced before assignment
Traceback (most recent call last):
  File "main.py", line 168, in updateinfo
UnboundLocalError: local variable 'info' referenced before assignment
Traceback (most recent call last):
  File "main.py", line 168, in updateinfo
UnboundLocalError: local variable 'info' referenced before assignment
Traceback (most recent call last):
  File "main.py", line 169, in updateinfo
UnboundLocalError: local variable 'info' referenced before assignment
Traceback (most recent call last):
  File "main.py", line 169, in updateinfo
UnboundLocalError: local variable 'info' referenced before assignment
Traceback (most recent call last):
  File "main.py", line 169, in updateinfo
UnboundLocalError: local variable 'info' referenced before assignment
Traceback (most recent call last):
  File "main.py", line 169, in updateinfo
UnboundLocalError: local variable 'info' referenced before assignment
Traceback (most recent call last):
  File "main.py", line 169, in updateinfo
UnboundLocalError: local variable 'info' referenced before assignment
Traceback (most recent call last):
  File "main.py", line 169, in updateinfo
UnboundLocalError: local variable 'info' referenced before assignment
Traceback (most recent call last):
  File "main.py", line 169, in updateinfo
UnboundLocalError: local variable 'info' referenced before assignment
Traceback (most recent call last):
  File "main.py", line 169, in updateinfo
UnboundLocalError: local variable 'info' referenced before assignment
Traceback (most recent call last):
  File "main.py", line 169, in updateinfo
UnboundLocalError: local variable 'info' referenced before assignment
Traceback (most recent call last):
  File "main.py", line 169, in updateinfo
UnboundLocalError: local variable 'info' referenced before assignment
Traceback (most recent call last):
  File "main.py", line 169, in updateinfo
UnboundLocalError: local variable 'info' referenced before assignment
Traceback (most recent call last):
  File "main.py", line 169, in updateinfo
UnboundLocalError: local variable 'info' referenced before assignment
Traceback (most recent call last):
  File "main.py", line 169, in updateinfo
UnboundLocalError: local variable 'info' referenced before assignment
Traceback (most recent call last):
  File "main.py", line 169, in updateinfo
UnboundLocalError: local variable 'info' referenced before assignment
Traceback (most recent call last):
  File "main.py", line 169, in updateinfo
UnboundLocalError: local variable 'info' referenced before assignment
Traceback (most recent call last):
  File "main.py", line 169, in updateinfo
UnboundLocalError: local variable 'info' referenced before assignment
